# @name get-prompts
GET http://localhost:3333/prompts

###

# @name upload-video
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="example.mp3"
Content-Type: audio/mp3

< ./audio.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# @name create-transcription
POST http://localhost:3333/videos/d8c7f7d6-3ad5-4656-af6d-7a5d39e44a7b/transcription
Content-Type: application/json

{
  "prompt": "desenvolvedor , conselhos, início de carreira"
}

###

# @name generate-ai-completion
POST http://localhost:3333/ai/generate
Content-Type: application/json

{
  "videoId": "d8c7f7d6-3ad5-4656-af6d-7a5d39e44a7b",
  "temperature": 0.5,
  "template": "Gere um resumo sucinto da transcrição do vídeo informada a seguir: '''{transcription}'''"
}